version: "3.7"

services:
    postgres:
      container_name: postgres
      image: postgres
      restart: unless-stopped
      volumes:
        - postgres-data:/data
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRESQL_USER}
        POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      ports:
        - ${POSTGRESQL_PORT}:5432


    prisma:
      container_name: prisma
      links:
        - postgres
      depends_on:
        - postgres
      ports:
        - 5555:5555
      build:
        context: ./prisma
        dockerfile: Dockerfile
      environment:
        DATABASE_URL: ${DATABASE_URL}
      volumes:
        - /app/prisma

    backend:
      container_name: backend
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - DATABASE_URL=${DATABASE_URL}
      volumes:
        - .:/app
        - /app/node_modules
        - /app/prisma
      links:
        - postgres
      depends_on:
        - postgres
        - prisma
      ports:
        - 4000:4000
      environment:
        DATABASE_URL: ${DATABASE_URL}

volumes:
  postgres-data:

